let japanese: [String: String] = [
    "Back to workspace": "ワークスペースに戻る",
    "General": "一般",
    "App theme": "アプリテーマ",
    "Choose which theme the application interface should use.": "アプリケーションインターフェースで使用するテーマを選択してください。",
    "Language": "言語",
    "Choose the display language used by the application UI.": "アプリケーションUIの表示言語を選択してください。",
    "Interface zoom": "インターフェースのズーム",
    "Adjust the overall size of text and controls in the current window.": "現在のウィンドウ内のテキストとコントロールの全体的なサイズを調整します。",
    "Inherit system terminal profile": "システムターミナルプロファイルを継承",
    "When launching the built-in terminal, inherit login shell environment, proxy, Kubernetes variables, and local terminal font when possible.": "組み込みターミナルを起動する際に、ログインシェル環境、プロキシ、Kubernetes変数、およびローカルターミナルフォントを可能な限り継承します。",
    "Terminal font": "ターミナルフォント",
    "Leave blank to auto-detect system terminal settings; set a value to override the MiMo terminal font.": "空白のままにするとシステムターミナル設定を自動検出します。値を設定するとMiMoターミナルフォントを上書きします。",
    "e.g. MesloLGS NF": "例: MesloLGS NF",
    "Current: %@ (inherited)": "現在: %@（継承済み）",
    "Current: %@": "現在: %@",
    "Code preview": "コードプレビュー",
    "Model settings": "モデル設定",
    "Providers": "プロバイダー",
    "Skills": "スキル",
    "MCP Servers": "MCPサーバー",
    "Plugins": "プラグイン",
    "Commands": "コマンド",
    "Indexing": "インデックス作成中",
    "Usage": "使用量",
    "Terminal": "ターミナル",
    "Git": "Git",
    "Welcome to MiCoder Terminal": "MiCoder Terminalへようこそ",
    "Type \"help\" for commands": "コマンドを表示するには\"help\"と入力してください",
    "Available commands: clear, help, ls, pwd": "利用可能なコマンド: clear、help、ls、pwd",
    "Command not found: %@": "コマンドが見つかりません: %@",
    "Git tools": "Gitツール",
    "Changes": "変更",
    "No changes": "変更なし",
    "Branch": "ブランチ",
    "Commit": "コミット",
    "Auto-generate from changes": "変更から自動生成",
    "Write custom message": "カスタムメッセージを入力",
    "Review & Push": "レビューとプッシュ",
    "Publish": "公開",
    "Publish to GitHub": "GitHubに公開",
    "Repository name": "リポジトリ名",
    "Initialize Git Repository": "Gitリポジトリを初期化",
    "Visibility": "公開範囲",
    "Public": "パブリック",
    "Private": "プライベート",
    "Initialize": "初期化",
    "Session busy, aborting and retrying...": "セッションがビジー状態です。中断して再試行しています...",
    "Install GitHub CLI": "GitHub CLIをインストール",
    "Install with Homebrew": "Homebrewでインストール",
    "Sign in to GitHub": "GitHubにサインイン",
    "Sign in with browser": "ブラウザでサインイン",
    "Create & Push": "作成してプッシュ",
    "Cancel": "キャンセル",
    "Create a local Git repository for this workspace. You can publish it to GitHub afterwards.": "このワークスペースのローカルGitリポジトリを作成します。後でGitHubに公開できます。",
    "Your comment": "コメント",
    "What did you change? (optional)": "何を変更しましたか？（任意）",
    "Auto summary of changes": "変更の自動要約",
    "Commit & Push": "コミットとプッシュ",
    "Open install docs": "インストールドキュメントを開く",
    "Plan": "プラン",
    "No steps yet": "ステップはまだありません",
    "%d completed": "%d件完了",
    "%d waiting": "%d件待機中",
    "Idle": "アイドル",
    "Generating...": "生成中...",
    "Processing...": "処理中...",
    "New Project": "新規プロジェクト",
    "Project Name": "プロジェクト名",
    "Folder": "フォルダ",
    "Choose Folder": "フォルダを選択",
    "Create Project": "プロジェクトを作成",
    "Notifications": "通知",
    "No notifications": "通知はありません",
    "Task completions and system alerts will appear here.": "タスクの完了とシステムアラートがここに表示されます。",
    "Workspaces": "ワークスペース",
    "No tasks yet": "タスクはまだありません",
    "now": "たった今",
    "Storage": "ストレージ",
    "Database": "データベース",
    "Snapshots": "スナップショット",
    "Messages": "メッセージ",
    "Active sessions": "アクティブセッション",
    "Archived sessions": "アーカイブ済みセッション",
    "Cleanup": "クリーンアップ",
    "Delete chats older than:": "次の期間より古いチャットを削除：",
    "7 days": "7日",
    "30 days": "30日",
    "90 days": "90日",
    "180 days": "180日",
    "1 year": "1年",
    "Delete old chats?": "古いチャットを削除しますか？",
    "This will permanently delete all chats older than %d days, including their messages. This action cannot be undone.": "%d日より古いすべてのチャットとそのメッセージを完全に削除します。この操作は元に戻せません。",
    "Delete": "削除",
    "Delete all archived chats": "すべてのアーカイブ済みチャットを削除",
    "Compress database (VACUUM)": "データベースを圧縮（VACUUM）",
    "Reset storage": "ストレージをリセット",
    "Clear app cache": "アプリキャッシュをクリア",
    "Clear app cache?": "アプリキャッシュをクリアしますか？",
    "Reset": "リセット",
    "Archive now": "今すぐアーカイブ",
    "Active": "アクティブ",
    "Archived": "アーカイブ済み",
    "Archive": "アーカイブ",
    "Manage MiCoder Agent…": "MiCoder Agentを管理…",
    "Start a new task": "新しいタスクを開始",
    "Search tasks…": "タスクを検索…",
    "Filter": "フィルター",
    "Sort": "並べ替え",
    "Group": "グループ",
    "Project": "プロジェクト",
    "Overview": "概要",
    "Settings": "設定",
    "No workspaces": "ワークスペースがありません",
    "No matching workspaces": "一致するワークスペースがありません",
    "Recent use": "最近の使用",
    "Name": "名前",
    "Task count": "タスク数",
    "All": "すべて",
    "Has sessions": "セッションあり",
    "Empty": "空",
    "List": "リスト",
    "Grid": "グリッド",
    "Type to search…": "検索するには入力…",
    "Mark all read": "すべて既読にする",
    "Remove all": "すべて削除",
    "Mark read": "既読にする",
    "Delete project": "プロジェクトを削除",
    "Find new path": "新しいパスを検索",
    "Export backup": "バックアップをエクスポート",
    "Import backup": "バックアップをインポート",
    "Delete older than %d days": "%d日より古いものを削除",
    "Reset app cache": "アプリキャッシュをリセット",
    "Show line numbers": "行番号を表示",
    "Wrap long lines": "長い行を折り返す",
    "Code font size": "コードのフォントサイズ",
    "Smaller": "小",
    "Default": "デフォルト",
    "Larger": "大",
    "Dark": "ダーク",
    "Light": "ライト",
    "Theme": "テーマ",
    "Zoom": "ズーム",
    "Local providers": "ローカルプロバイダー",
    "Auto-detect": "自動検出",
    "Detecting…": "検出中…",
    "Add": "追加",
    "Address": "アドレス",
    "Models": "モデル",
    "Connect": "接続",
    "Checking…": "確認中…",
    "Connected": "接続済み",
    "Disconnected": "切断済み",
    "Reconnect": "再接続",
    "Refresh": "更新",
    "Loading…": "読み込み中…",
    "Uninstall": "アンインストール",
    "Install": "インストール",
    "Update available": "アップデートあり",
    "Enable": "有効にする",
    "Disable": "無効にする",
    "Search…": "検索…",
    "No results": "結果なし",
    "Version": "バージョン",
    "Back": "戻る",
    "Close": "閉じる",
    "Done": "完了",
    "Save": "保存",
    "Edit": "編集",
    "Copy": "コピー",
    "Paste": "貼り付け",
    "Cut": "切り取り",
    "Select All": "すべて選択",
    "Undo": "元に戻す",
    "Redo": "やり直す",
    "Retry": "再試行",
    "Continue": "続ける",
    "Help": "ヘルプ",
    "About": "について",
    "Version %@": "バージョン %@"
]
